services:
  db:
    build: ./db
    restart: always
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728
      - ./db/init.sql:/docker-entrypoint-initdb.d/01-extensions.sql
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: my-secret-pw
      POSTGRES_DB: db
